[build-system]
requires = ["setuptools>=61.0", "pybind11>=2.13.6,<3.0"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel.macos]
repair-wheel-command = "" # getting issues with unresolved files

[tool.cibuildwheel]
before-build = "pip install pybind11[global]"
skip = "*-musllinux_*"
