[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "livekit-agents"
dynamic = ["version"]
description = "LiveKit Python Agents"
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.9"
authors = [{ name = "LiveKit", email = "support@livekit.io" }]
keywords = ["webrtc", "realtime", "audio", "video", "livekit", "agents", "AI"]
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Multimedia :: Sound/Audio",
    "Topic :: Multimedia :: Video",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3 :: Only",
]
dependencies = [
    "click~=8.1",
    "livekit>=0.21.1",
    "livekit-api>=0.8.2",
    "livekit-protocol>=0.8.2",
    "protobuf>=3",
    "pyjwt>=2.0",
    "types-protobuf>=4,<5",
    "watchfiles>=1.0",
    "psutil>=7.0",
    "aiohttp~=3.10",
    "typing-extensions>=4.12",
    "sounddevice>=0.5",
    "docstring_parser>=0.16",
    "eval-type-backport",
    "colorama>=0.4.6",
]

[project.optional-dependencies]
codecs = ["av>=12.0.0", "numpy>=1.26.0"]
images = ["pillow>=10.3.0"]
aws = ["livekit-plugins-aws>=1.0.0.rc1"]
neuphonic = ["livekit-plugins-neuphonic>=1.0.0.rc1"]
playai = ["livekit-plugins-playai>=1.0.0.rc1"]
turn-detector = ["livekit-plugins-turn-detector>=1.0.0.rc1"]
llama-index = ["livekit-plugins-llama-index>=1.0.0.rc1"]
assemblyai = ["livekit-plugins-assemblyai>=1.0.0.rc1"]
rime = ["livekit-plugins-rime>=1.0.0.rc1"]
nltk = ["livekit-plugins-nltk>=1.0.0.rc1"]
anthropic = ["livekit-plugins-anthropic>=1.0.0.rc1"]
openai = ["livekit-plugins-openai>=1.0.0.rc1"]
browser = ["livekit-plugins-browser>=1.0.0.rc1"]
groq = ["livekit-plugins-groq>=1.0.0.rc1"]
elevenlabs = ["livekit-plugins-elevenlabs>=1.0.0.rc1"]
azure = ["livekit-plugins-azure>=1.0.0.rc1"]
fal = ["livekit-plugins-fal>=1.0.0.rc1"]
clova = ["livekit-plugins-clova>=1.0.0.rc1"]
deepgram = ["livekit-plugins-deepgram>=1.0.0.rc1"]
rag = ["livekit-plugins-rag>=1.0.0.rc1"]
silero = ["livekit-plugins-silero>=1.0.0.rc1"]
cartesia = ["livekit-plugins-cartesia>=1.0.0.rc1"]
speechmatics = ["livekit-plugins-speechmatics>=1.0.0.rc1"]
google = ["livekit-plugins-google>=1.0.0.rc1"]


[project.urls]
Documentation = "https://docs.livekit.io"
Website = "https://livekit.io/"
Source = "https://github.com/livekit/agents"

[tool.hatch.version]
path = "livekit/agents/version.py"

[tool.hatch.build.targets.wheel]
packages = ["livekit"]

[tool.hatch.build.targets.sdist]
include = ["/livekit"]

[tool.hatch.build.targets.wheel.shared-data]
"livekit/agents/debug/index.html" = "livekit/agents/debug/index.html"
