[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "livekit-plugins-telnyx"
version = "0.1.0"
description = "Telnyx implementation for LiveKit Agents"
dependencies = [
    "livekit-agents>=0.8.0",
    "livekit-api>=0.6.0"
]

[tool.hatch.build.targets.wheel]
packages = ["livekit"]
