[project]
name = "livekit-voice-agent"
version = "0.1.0"
requires-python = ">=3.9.0"
dependencies = [
    "livekit-agents[silero,turn-detector]~=1.2",
    "livekit-plugins-noise-cancellation~=0.2",
    "python-dotenv>=1.0.1",
]

[tool.uv.sources]
livekit-agents = { workspace = true }
