[settings.session]
allow_interruptions = true
min_interruption_duration = 0.1
min_endpointing_delay = 0.2
preemptive_generation = true

[settings.agents]
file = "agents.py"
class = "MyAgent"

[input.audio]
file = ""

[input.agent]
stt = "" # optional
llm = ""
tts = "" # optional

[input.events]
tts_events = []
llm_events = []
stt_events = []
vad_events = []
eou_events = []

[output.events]
expected = []
ordered = true
timestamp_tolerance = 0.1

[output.metrics]
file = "output_metrics.json"
