[settings]
plugin = "livekit.plugins.deepgram"
enable_pict = true

[vad.test_parameters]
# pass


[stt.test_parameters]
model = ["nova-3", "nova-2"]
language = ["en-US", "en-GB"]
interim_results = [true, false]
punctuate = [true, false]
smart_format = [true, false]

[llm.test_parameters]
# pass

[realtime.test_parameters]
# pass

[tts.test_parameters]
# pass
