[project]
name = "livekit-plugins-hedra"
description = "Agent Framework plugin for Hedra Avatar"
readme = "README.md"
requires-python = ">=3.9.0"
license = "Apache-2.0"
authors = [{ name = "LiveKit", email = "support@livekit.io" }]
keywords = [
  "ai",
  "audio",
  "avatar",
  "hedra",
  "livekit",
  "realtime",
  "video",
  "voice"
]
dependencies = ["livekit-agents>=1.4.0.rc1"]

[project.urls]
Documentation = "https://docs.livekit.io"
Source = "https://github.com/livekit/agents"
Website = "https://livekit.io/"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "livekit/plugins/hedra/version.py"

[tool.hatch.build.targets.wheel]
packages = ["livekit"]

[tool.hatch.build.targets.sdist]
include = ["/livekit"]
