[project]
name = "livekit-plugins-smallestai"
description = "Agent Framework plugin for speech synthesis with the Smallest AI."
readme = "README.md"
requires-python = ">=3.9.0"
license = "Apache-2.0"
authors = [{ name = "LiveKit", email = "hello@livekit.io" }]
keywords = [
  "audio",
  "livekit",
  "multilingual",
  "realtime",
  "smallestai",
  "tts",
  "video",
  "webrtc"
]
dependencies = ["livekit-agents[codecs]>=1.4.0.rc2", "numpy>=1.26"]
dynamic = ["version"]

[project.urls]
Documentation = "https://docs.livekit.io"
Source = "https://github.com/livekit/agents"
Website = "https://livekit.io/"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "livekit/plugins/smallestai/version.py"

[tool.hatch.build.targets.wheel]
packages = ["livekit"]

[tool.hatch.build.targets.sdist]
include = ["/livekit"]
